# Generated by Django 2.2.13 on 2021-01-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(blank=True, max_length=50)),
                ('score', models.IntegerField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Records',
                'verbose_name_plural': 'Records',
            },
        ),
    ]
